apiVersion: v1
kind: Service
metadata: 
  name: svc-mongo
  labels:
    app: svc-mongo
spec:
  type: NodePort
  selector:
    app: mongo-pod
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32000
