apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo-pod
spec:
  containers:
  - name: mongo-pod
    image: eduardosanches/mongo-fastfood:latest
    ports:
      - containerPort: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: MONGO_INITDB_ROOT_USERNAME
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: MONGO_INITDB_ROOT_PASSWORD
      - name: MONGO_INITDB_DATABASE
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: MONGO_INITDB_DATABASE