apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  MONGO_URI: mongodb://fiap:fastfood@svc-mongo:32000
  MONGO_DATABASE: fiapdb

  MONGO_INITDB_ROOT_USERNAME: fiap
  MONGO_INITDB_ROOT_PASSWORD: fastfood
  MONGO_INITDB_DATABASE: fiapdb