apiVersion: v1
kind: Secret
metadata:
  name: sc-default
type: Opaque
stringData:
  MONGO_URI: "mongodb://fiap:fastfood@ac-un7na5c-shard-00-01.kyofdjy.mongodb.net:27017/?ssl=true&retryWrites=true&loadBalanced=false&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=fiapdb&authMechanism=SCRAM-SHA-1"
  MONGO_DATABASE: fiapdb
