apiVersion: v1
kind: Secret
metadata:
  name: sc-default
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://fiap@fiapcluster0.kyofdjy.mongodb.net/admin?retryWrites=true&loadBalanced=false&replicaSet=atlas-cb5ho3-shard-0&readPreference=primary&srvServiceName=mongodb&connectTimeoutMS=10000&w=majority&authSource=admin&authMechanism=SCRAM-SHA-1&3t.uriVersion=3&3t.connection.name=fiap-atlas&3t.databases=admin&3t.alwaysShowAuthDB=true&3t.alwaysShowDBFromUserRole=true&3t.sslTlsVersion=TLS"
  MONGO_DATABASE: fiapdb
