apiVersion: v1
kind: Service
metadata:
  name: svc-fastfood
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: ms-fastfood
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
#    nodePort: 30010
    
