spring:
  application:
    name: fastfood
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://fiap-app:6kdCoHWLbCyMnmOw@ac-un7na5c-shard-00-01.kyofdjy.mongodb.net:27017/?ssl=true&retryWrites=true&loadBalanced=false&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=fiapdb&authMechanism=SCRAM-SHA-1}
      database: fiapdb
      ssl:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

