management:
  endpoint:
    health:
      enabled: true

spring:
  application:
    name: fastfood
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

