spring:
  application:
    name: fastfood
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: fiapdb
      ssl:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

