spring:
  application:
    name: fastfood
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:root@localhost:27017}
      database: local
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

